language: node_js

node_js:
 - "8"

script:
 - yarn run lint
 - yarn run flow
 - yarn test

before_deploy:
 - yarn run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: gIvFSK+4FR/ItSP3IIiudDU7X443lOWl0kEquteRzkB0uPMV+lZ1hv8JRCK3sL/iajTQWgxwb09aw05EtRgOJFW8cOP4iRniuivQCX0dySKQm2OBXs0hLC5tBP+rexoYVNJYk3eTH105fvey5mSNgLjsBe6XSnwTBwme7aNIDTRkzQzT8PHEFJDf4GdESaWVkYZqcymEgpMGiQ5lBThITJm7yL66E1lzGkREXGyzJUFcCitBYGzFXivCykMP85zv3bICSTYt+Ue3F18Gy8IUA/qK4eklAADkW6WlwJxFHiLk6rv8ajjut3JN75htnnTWaIdTFnozF3ELlns/wAr4hEznz08z+/uzVtZN72kYsRt74uHopC1DvNXiQBEnKdzmC3X+bwk94kp5qaCr/o/ESrt0NkJ2lLZo4C5SBj88AuD7evXKx3iq5Rl5m+1sSgMv5fejmbkW7/n2LTTuvQd+hChEL/yMIADOAloOdb1AQtKtZNY/YhFfCtbo60Z0dS/aOvcZmzc7ynANn+16l5T4TUE+sxNXzvBlCe9E/yfp0GjYAgoUhU21M361R+J548V04rjtZz4gl14svSZd2ZAhMt7qqy5CjjQql9Vc2weXMt/wVLTxFLXyiO3yMAiiRccSa4cBbS/YNTfDwgHJcbX9elBRoyGifccqV8FAxH5Tm4Y=
  message: "Deployed by Travis CI."
