language: node_js

node_js:
 - "8"

script:
 - yarn run lint
 - yarn run flow
 - yarn test

before_deploy:
 - yarn run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: lN2rERPHS0De0sl/dGp1LwMaTjsgaBm4NemU2P7MMBO/UgKhETWxd5EPO7aw220J3guG/FrH8VzO5D3OQOsOAmgMsLftDeOJYWI6X+l+xhvnMlHRY5WNjHhAS2SboJvBG72xbx6zybdlBLz/zbEENxdGDg+5V3EogwRctr3eu3jz2GIw10cZw6OuySw5UyXMyICFpV1XdnQ7/1CuwNaIvTh7ZRnNsi2rDlUbwPQpkkQhGYEcmKtBGFzGY/+2kN/89i1iZIOduiKIz9Joo77bWiIz0k+yygPUHVnmWugty0rwvXYBVyu5V4KH8k1Ayw5yRDSgmK1MiNkWPyOgc6dO/Sj+iDD2OIl+WNf3dS9wYeaCgsdKIR7tunGa8fJH2tif8Ilm7AoAHNJ+M/T/S0WNkTwO9v2NIDSwTvwHRR8hoj2YVDuznG4IJMCvaPCuOYz/16KkaQs03DUxx5b4QewbadkdhW+pApoqRZ2fTaEp341L2LAikz/HAlMr0L41AlLDgIGhlVbA23F33sOjJO/oQc/0E8exB8nnGT+j/qIxdMMA3nJ4OAm+V4JYeqnWmEvyrdx3LtGtmGxYAA05UmJyE+EN96hpFI8qpNK0EXya6tdW/7EyIHqoLdEOsd5Rij74YhDIJlj4e+msHvL+WkFC5wnDaVEyMEtk0xVncw74/MY=
  message: "Deployed by Travis CI."
