// flow-typed signature: 529cfe6e5c4122656f6a22a64cfb46ec
// flow-typed version: <<STUB>>/redux-devtools-inspector_vcooperka/redux-devtools-inspector#cdb11f9fd2b118b62e249f9dd58329c1e8f9a639/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-inspector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-inspector/demo/src/js/DemoApp' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/demo/src/js/getOptions' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/demo/src/js/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/demo/src/js/reducers' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-plugin-react-transform_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/babel-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/base16_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/chokidar_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/clean-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/dateformat_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/export-files-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/git-directory-deploy_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/hex-rgba_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/html-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/imports-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/javascript-stringify_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/json-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/jsondiffpatch_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/jss_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/jss-nested_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/jss-vendor-prefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/lodash.debounce_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/lodash.shuffle_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/nyan-progress-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/pre-commit_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/raw-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-base16-styling_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-bootstrap_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-input-enhancements_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-json-tree_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-pure-render_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-redux_v4.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-router_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-router-redux_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/react-transform-hmr_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/redux-devtools_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/redux-devtools-dock-monitor_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/redux-devtools-themes_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/redux-logger_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/ActionList' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/ActionListHeader' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/ActionListRow' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/ActionPreview' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/ActionPreviewHeader' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/createDiffPatcher' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/DevtoolsInspector' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/redux' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/RightSlider' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/tabs/ActionTab' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/tabs/DiffTab' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/tabs/getItemString' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/tabs/getJsonTreeTheme' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/tabs/JSONDiff' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/tabs/StateTab' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/themes/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/themes/inspector' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/types' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/utils/createStylingFromTheme' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/utils/getInspectedState' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/utils/getType' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/lib/utils/isIterable' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/ActionList' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/ActionListHeader' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/ActionListRow' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/ActionPreview' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/ActionPreviewHeader' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/createDiffPatcher' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/DevtoolsInspector' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/redux' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/RightSlider' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/tabs/ActionTab' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/tabs/DiffTab' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/tabs/getItemString' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/tabs/getJsonTreeTheme' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/tabs/JSONDiff' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/tabs/StateTab' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/themes/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/themes/inspector' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/types' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/utils/createStylingFromTheme' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/utils/getInspectedState' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/utils/getType' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/src/utils/isIterable' {
  declare module.exports: any;
}

declare module 'redux-devtools-inspector/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-inspector/demo/src/js/DemoApp.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/demo/src/js/DemoApp'>;
}
declare module 'redux-devtools-inspector/demo/src/js/getOptions.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/demo/src/js/getOptions'>;
}
declare module 'redux-devtools-inspector/demo/src/js/index.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/demo/src/js/index'>;
}
declare module 'redux-devtools-inspector/demo/src/js/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/demo/src/js/reducers'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-plugin-react-transform_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-plugin-react-transform_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/babel-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/babel-runtime_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/base16_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/base16_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/chokidar_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/chokidar_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/clean-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/clean-webpack-plugin_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/dateformat_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/dateformat_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/eslint-loader_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/export-files-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/export-files-webpack-plugin_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/git-directory-deploy_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/git-directory-deploy_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/hex-rgba_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/hex-rgba_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/html-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/html-webpack-plugin_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/imports-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/imports-loader_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/javascript-stringify_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/javascript-stringify_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/json-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/json-loader_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/jsondiffpatch_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/jsondiffpatch_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/jss_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/jss_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/jss-nested_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/jss-nested_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/jss-vendor-prefixer_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/jss-vendor-prefixer_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/lodash.debounce_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/lodash.debounce_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/lodash.shuffle_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/lodash.shuffle_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/nyan-progress-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/nyan-progress-webpack-plugin_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/pre-commit_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/pre-commit_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/raw-loader_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/raw-loader_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-base16-styling_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-base16-styling_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-bootstrap_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-bootstrap_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-input-enhancements_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-input-enhancements_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-json-tree_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-json-tree_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-pure-render_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-pure-render_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-redux_v4.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-redux_v4.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-router_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-router_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-router-redux_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-router-redux_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/react-transform-hmr_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/react-transform-hmr_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/redux-devtools_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/redux-devtools_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/redux-devtools-dock-monitor_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/redux-devtools-dock-monitor_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/redux-devtools-themes_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/redux-devtools-themes_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/redux-logger_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/redux-logger_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'redux-devtools-inspector/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/flow-typed/npm/webpack-dev-server_vx.x.x'>;
}
declare module 'redux-devtools-inspector/lib/ActionList.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/ActionList'>;
}
declare module 'redux-devtools-inspector/lib/ActionListHeader.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/ActionListHeader'>;
}
declare module 'redux-devtools-inspector/lib/ActionListRow.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/ActionListRow'>;
}
declare module 'redux-devtools-inspector/lib/ActionPreview.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/ActionPreview'>;
}
declare module 'redux-devtools-inspector/lib/ActionPreviewHeader.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/ActionPreviewHeader'>;
}
declare module 'redux-devtools-inspector/lib/createDiffPatcher.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/createDiffPatcher'>;
}
declare module 'redux-devtools-inspector/lib/DevtoolsInspector.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/DevtoolsInspector'>;
}
declare module 'redux-devtools-inspector/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/index'>;
}
declare module 'redux-devtools-inspector/lib/redux.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/redux'>;
}
declare module 'redux-devtools-inspector/lib/RightSlider.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/RightSlider'>;
}
declare module 'redux-devtools-inspector/lib/tabs/ActionTab.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/tabs/ActionTab'>;
}
declare module 'redux-devtools-inspector/lib/tabs/DiffTab.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/tabs/DiffTab'>;
}
declare module 'redux-devtools-inspector/lib/tabs/getItemString.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/tabs/getItemString'>;
}
declare module 'redux-devtools-inspector/lib/tabs/getJsonTreeTheme.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/tabs/getJsonTreeTheme'>;
}
declare module 'redux-devtools-inspector/lib/tabs/JSONDiff.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/tabs/JSONDiff'>;
}
declare module 'redux-devtools-inspector/lib/tabs/StateTab.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/tabs/StateTab'>;
}
declare module 'redux-devtools-inspector/lib/themes/index.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/themes/index'>;
}
declare module 'redux-devtools-inspector/lib/themes/inspector.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/themes/inspector'>;
}
declare module 'redux-devtools-inspector/lib/types.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/types'>;
}
declare module 'redux-devtools-inspector/lib/utils/createStylingFromTheme.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/utils/createStylingFromTheme'>;
}
declare module 'redux-devtools-inspector/lib/utils/getInspectedState.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/utils/getInspectedState'>;
}
declare module 'redux-devtools-inspector/lib/utils/getType.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/utils/getType'>;
}
declare module 'redux-devtools-inspector/lib/utils/isIterable.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/lib/utils/isIterable'>;
}
declare module 'redux-devtools-inspector/src/ActionList.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/ActionList'>;
}
declare module 'redux-devtools-inspector/src/ActionListHeader.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/ActionListHeader'>;
}
declare module 'redux-devtools-inspector/src/ActionListRow.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/ActionListRow'>;
}
declare module 'redux-devtools-inspector/src/ActionPreview.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/ActionPreview'>;
}
declare module 'redux-devtools-inspector/src/ActionPreviewHeader.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/ActionPreviewHeader'>;
}
declare module 'redux-devtools-inspector/src/createDiffPatcher.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/createDiffPatcher'>;
}
declare module 'redux-devtools-inspector/src/DevtoolsInspector.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/DevtoolsInspector'>;
}
declare module 'redux-devtools-inspector/src/index.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/index'>;
}
declare module 'redux-devtools-inspector/src/redux.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/redux'>;
}
declare module 'redux-devtools-inspector/src/RightSlider.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/RightSlider'>;
}
declare module 'redux-devtools-inspector/src/tabs/ActionTab.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/tabs/ActionTab'>;
}
declare module 'redux-devtools-inspector/src/tabs/DiffTab.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/tabs/DiffTab'>;
}
declare module 'redux-devtools-inspector/src/tabs/getItemString.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/tabs/getItemString'>;
}
declare module 'redux-devtools-inspector/src/tabs/getJsonTreeTheme.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/tabs/getJsonTreeTheme'>;
}
declare module 'redux-devtools-inspector/src/tabs/JSONDiff.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/tabs/JSONDiff'>;
}
declare module 'redux-devtools-inspector/src/tabs/StateTab.jsx' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/tabs/StateTab'>;
}
declare module 'redux-devtools-inspector/src/themes/index.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/themes/index'>;
}
declare module 'redux-devtools-inspector/src/themes/inspector.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/themes/inspector'>;
}
declare module 'redux-devtools-inspector/src/types.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/types'>;
}
declare module 'redux-devtools-inspector/src/utils/createStylingFromTheme.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/utils/createStylingFromTheme'>;
}
declare module 'redux-devtools-inspector/src/utils/getInspectedState.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/utils/getInspectedState'>;
}
declare module 'redux-devtools-inspector/src/utils/getType.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/utils/getType'>;
}
declare module 'redux-devtools-inspector/src/utils/isIterable.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/src/utils/isIterable'>;
}
declare module 'redux-devtools-inspector/webpack.config.js' {
  declare module.exports: $Exports<'redux-devtools-inspector/webpack.config'>;
}
